site_name: Amber Cottage
site_url: http://ambercottage.top/
site_description: Amber Cottage, knowledge worth spreading and sharing.
site_author: AutuanLiu

repo_url: https://github.com/AutuanLiu/Machine-Learning-on-docker
edit_uri: ""

remote_name: origin
remote_branch: master

theme:
    name: mkdocs
    custom_dir: flatly/
    include_sidebar: true

markdown_extensions:
   # other extensions ...
   - pymdownx.arithmatex
   - toc
   - admonition

extra_css:
   - https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.css

extra_javascript:
  # other extra java script
  - https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.js
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML


nav:
    - Home: index.md
    - 数据科学:
        - 探索性数据分析: 数据科学/ExploratoryDataAnalysis.md
        - 数据可视化分析: 数据科学/visualization.md
        - 处理类别不均衡: 数据科学/imbalance.md
        - 数据科学基本路径: 数据科学/path.md
        - Docker基础: 数据科学/docker.md
    - 机器学习:
        - 广义线性模型(GLM): 机器学习/GeneralizedLinearModels.md
        - 不平衡类学习: 机器学习/imblearnDoc.md
        - 无监督学习: 机器学习/unsupervised.md
        - 模型选择: 机器学习/model.md
        - SkLearn的结构: 机器学习/sklearnStruct.md
        - 学习资料总结: 机器学习/content.md
    - 深度学习:
        - CNN: 深度学习/CNN.md
        - RNN: 深度学习/RNN.md
        - TensorFlow: 深度学习/tensorflow.md
    - Blog:
        - 贝叶斯思想: Blog/Bayesian.md
        - Python 随笔01: Blog/Iterator.md
        - matplotlib-Object-oriented: Blog/matplotlib.md
        - 机器学习随笔01:: Blog/ml.md
    - About:
        - AboutMe: About/aboutme.md
        - License: About/license.md

copyright: Copyright &copy; 2017-2018 <a href="http://ambercottage.top/">AutuanLiu</a>
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
